ENV: "swibrid"
SNAKEOPTS: "-j 100 -k --rerun-incomplete --latency-wait 60 -p --retries 10" 
STUDY: "current_study"
INPUT: ""
SAMPLE_SHEET: ""
SAMPLES: ["sample1","sample2"]
MINLENGTH: 500
BARCODES_PRIMERS: 'index/barcodes_primers.fa'
GENOME: 'hs1'
REFERENCE: 'hs1.fa'
SWITCH: 'chr14:99840000-100138000:-'
ANNOTATION: 'index/chm13.draft_v2.0.gene_annotation.exon_shorted.bed'
SWITCH_ANNOTATION: 'index/hs1_switch_regions.bed'
VARIANT_ANNOTATION: 'index/chm13v2.0_dbSNPv155.switch.vcf.gz'
LAST_INDEX: 'index/hs1db'
MINIMAP_INDEX: 'index/hs1-ont.mmi'
ALIGNER: 'LAST'
TELO_REPEAT: 'index/telomerSequence.fasta'
NMAX: 50000
MAX_GAP: 75
BINSIZE: 50
BLACKLIST_REGIONS: 'index/hs1_blacklist_regions.bed'
WEIGHTS: 'cluster'
CLUSTERING_METRIC: 'cosine'
CLUSTERING_METHOD: 'average'
CLUSTERING_CUTOFF: 0.01
