# CONFIG FILE FOR SWIBRID
#
# name of conda environment (will be passed to snakemake)
ENV: "swibrid"
# default options to pass to snakemake
SNAKEOPTS: "-j 100 -k --rerun-incomplete --latency-wait 60 -p --retries 10" 
# study name
STUDY: "current_study"
# input fastq file (if demultiplexing is included)
INPUT: ""
# sample sheet specifying barcodes and associated sample names
SAMPLE_SHEET: ""
# fasta file with barcodes and primers used during demultiplexing 
BARCODES_PRIMERS: 'index/barcodes_primers.fa'
# list of samples for which  to run the pipeline
SAMPLES: ["sample1","sample2"]
# minimum read length
MINLENGTH: 500
# reference genome (fasta file, index should be present)
REFERENCE: 'index/hs1.fa'
# LAST index of reference genome
LAST_INDEX: 'index/hs1db'
# minimap2 index of reference genome
MINIMAP_INDEX: 'index/hs1-ont.mmi'
# aligner to use (LAST is more precise and recommended, minimap2 is much faster)
ALIGNER: 'LAST'
# fasta file specifying the telomer repeat unit
TELO_REPEAT: 'index/telomerSequence.fasta'
# coordinates of switch region (altogether)
SWITCH: 'chr14:99840000-100138000:-'
# bed file with coordinates of individual switch regions
SWITCH_ANNOTATION: 'index/hs1_switch_regions.bed'
# bed file with gene annotation
ANNOTATION: 'index/chm13.draft_v2.0.gene_annotation.exon_shorted.bed'
# vcf file with variant annotation
VARIANT_ANNOTATION: 'index/chm13v2.0_dbSNPv155.switch.vcf.gz'
# max number of reads to cluster
NMAX: 50000
# clustering metric to use 
CLUSTERING_METRIC: 'cosine'
# clustering method to use
CLUSTERING_METHOD: 'average'
# fixed clustering cutoff
CLUSTERING_CUTOFF: 0.01
# max gap size to remove before clustering
MAX_GAP: 75
# bin size for breakpoint analysis
BINSIZE: 50
# blacklisted regions for insert detection
BLACKLIST_REGIONS: 'index/hs1_blacklist_regions.bed'
# weights to use for averaging features over clusters (or reads)
WEIGHTS: 'cluster'
# number of reads to use for downsampling analysis
CLUSTER_DOWNSAMPLING_NREADS: 1000
# number of replicates used in downsampling
CLUSTER_DOWNSAMPLING_NREPS: 10
