ENV: "swibrid"
CONDA: "$HOME/miniconda/envs"
STUDY: "test_study"
INPUT: ""
SAMPLE_SHEET: ""
SAMPLES: [""]
MINLENGTH: 500
BARCODES_PRIMERS: 'index/barcodes_primers.fa'
GENOME: 'hg19'
REFERENCE: 'index/hg19.fa'
SWITCH: 'chr14:106050000-106337000:-'
ANNOTATION: 'index/gencode.v19.annotation.exon.gene_shortedV2.bed'
SWITCH_ANNOTATION: 'hg19_switch_regions.bed'
LASTINDEX: 'index/hg19db'
TELO_REPEAT: 'index/telomerSequence.fasta'
EFF_CLUSTER_CUTOFF: .95
NMAX: 200000
N_NEIGHBORS: 500
GBBS_BIN: '$HOME/gbbs/bazel-bin'
MAX_GAP: 75
BINSIZE: 50
BLACKLIST_REGIONS: 'index/hg19_blacklist_regions.bed'
