name: Publish Docs

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify the Python version you need

    - name: Install dependencies
      run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme sphinxcontrib-autoprogram
          python -m pip install biopython fastcluster logzero matplotlib numpy openpyxl pandas pysam python-dateutil fastjsonschema python-json-logger ruamel.yaml scikit-learn scipy tabulate


    - name: Build documentation
      run: |
        cd docs
        make clean
        make html  # Adjust this command if you use a different tool to generate your docs

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html  # Adjust this path to where your built HTML is located
